# Generated by Django 4.1.1 on 2023-12-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('provider', models.CharField(blank=True, default=True, max_length=50)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('paymenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttype')),
            ],
        ),
    ]
