# Generated by Django 4.1.1 on 2024-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='value',
            field=models.CharField(choices=[('COD', 'Cash On Delivery')], max_length=50),
        ),
    ]
