# Generated by Django 4.1.1 on 2024-03-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymenttype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
