# Generated by Django 4.1.1 on 2024-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentmethod_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
