# Generated by Django 4.1.1 on 2024-01-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='addess_type',
            field=models.CharField(choices=[('BL', 'Billing'), ('SP', 'Shipping')], default='BL', max_length=200),
        ),
    ]
