# Generated by Django 4.1.1 on 2024-01-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_addressbook_addess_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='addess_type',
            field=models.CharField(choices=[('BL', 'Billing'), ('SP', 'Shipping')], default='SP', max_length=200),
        ),
    ]
