# Generated by Django 4.1.1 on 2024-01-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_addressbook_addess_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='addess_type',
            new_name='address_type',
        ),
    ]
