# Generated by Django 4.1.1 on 2024-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_addressbook_first_name_addressbook_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='is_default',
            new_name='bill_default',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='ship_default',
            field=models.BooleanField(default=False),
        ),
    ]
