# Generated by Django 4.1.1 on 2024-01-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_is_default_addressbook_bill_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
