# Generated by Django 4.1.1 on 2024-01-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_addressbook_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
