# Generated by Django 4.1.1 on 2024-02-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_addressbook_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
