# Generated by Django 4.1.1 on 2024-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_delivered_carrier_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_delivered_customer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
