# Generated by Django 4.1.1 on 2024-03-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('archived', 'Archived - not available anymore')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
