# Generated by Django 4.1.1 on 2024-03-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_delete_shippingmethod_order_is_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
