# Generated by Django 4.1.1 on 2024-01-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.wishlistitem', unique=True),
        ),
    ]
