# Generated by Django 4.1.1 on 2024-01-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('basket', '0003_alter_wishlist_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.subproduct'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WishListItem',
        ),
    ]
